import type { MediaSectorSlug } from "@/data-sources/news/media-types";

export type RssSourceTier =
  "PRIMARY_TRADE" | "MAJOR_GENERAL" | "SPECIALIST" | "OFFICIAL";

export type RssFeedDefinition = {
  slug: string;
  name: string;
  sector: MediaSectorSlug;
  feedUrl: string;
  publisherDomain: string;
  enabled: boolean;
  tier: RssSourceTier;
  geography: string | null;
  notes: string;
};

export const RSS_FEEDS = [
  {
    slug: "music-business-worldwide",
    name: "Music Business Worldwide",
    sector: "music",
    feedUrl: "https://www.musicbusinessworldwide.com/feed/",
    publisherDomain: "musicbusinessworldwide.com",
    enabled: true,
    tier: "PRIMARY_TRADE",
    geography: null,
    notes: "Music business trade coverage.",
  },
  {
    slug: "billboard",
    name: "Billboard",
    sector: "music",
    feedUrl: "https://www.billboard.com/feed/",
    publisherDomain: "billboard.com",
    enabled: true,
    tier: "PRIMARY_TRADE",
    geography: "US",
    notes: "Music industry and chart news.",
  },
  {
    slug: "nme-music",
    name: "NME Music",
    sector: "music",
    feedUrl: "https://www.nme.com/news/music/feed",
    publisherDomain: "nme.com",
    enabled: true,
    tier: "SPECIALIST",
    geography: "GB",
    notes: "Music news feed.",
  },
  {
    slug: "pitchfork-news",
    name: "Pitchfork News",
    sector: "music",
    feedUrl: "https://pitchfork.com/feed/feed-news/rss",
    publisherDomain: "pitchfork.com",
    enabled: true,
    tier: "SPECIALIST",
    geography: "US",
    notes: "Recorded and live music news.",
  },
  {
    slug: "variety-film",
    name: "Variety Film",
    sector: "film",
    feedUrl: "https://variety.com/v/film/feed/",
    publisherDomain: "variety.com",
    enabled: true,
    tier: "PRIMARY_TRADE",
    geography: "US",
    notes: "Film trade reporting.",
  },
  {
    slug: "deadline-film",
    name: "Deadline Film",
    sector: "film",
    feedUrl: "https://deadline.com/v/film/feed/",
    publisherDomain: "deadline.com",
    enabled: true,
    tier: "PRIMARY_TRADE",
    geography: "US",
    notes: "Film business and production news.",
  },
  {
    slug: "hollywood-reporter-movies",
    name: "The Hollywood Reporter Movies",
    sector: "film",
    feedUrl: "https://www.hollywoodreporter.com/c/movies/movie-news/feed/",
    publisherDomain: "hollywoodreporter.com",
    enabled: true,
    tier: "PRIMARY_TRADE",
    geography: "US",
    notes: "Movie industry news.",
  },
  {
    slug: "indiewire-film",
    name: "IndieWire Film",
    sector: "film",
    feedUrl: "https://www.indiewire.com/c/film/news/feed/",
    publisherDomain: "indiewire.com",
    enabled: true,
    tier: "SPECIALIST",
    geography: "US",
    notes: "Independent film and industry news.",
  },
  {
    slug: "playbill",
    name: "Playbill",
    sector: "theatre",
    feedUrl: "https://playbill.com/rss/news",
    publisherDomain: "playbill.com",
    enabled: true,
    tier: "SPECIALIST",
    geography: "US",
    notes: "Theatre news.",
  },
  {
    slug: "broadwayworld",
    name: "BroadwayWorld",
    sector: "theatre",
    feedUrl: "https://www.broadwayworld.com/rss/newsroom.cfm",
    publisherDomain: "broadwayworld.com",
    enabled: false,
    tier: "SPECIALIST",
    geography: "US",
    notes: "Disabled after live validation returned HTTP 403.",
  },
  {
    slug: "theatermania",
    name: "TheaterMania",
    sector: "theatre",
    feedUrl: "https://www.theatermania.com/feed/",
    publisherDomain: "theatermania.com",
    enabled: false,
    tier: "SPECIALIST",
    geography: "US",
    notes: "Disabled after the endpoint returned no parseable feed items.",
  },
  {
    slug: "artshub-australia",
    name: "ArtsHub Australia",
    sector: "theatre",
    feedUrl: "https://www.artshub.com.au/feed/",
    publisherDomain: "artshub.com.au",
    enabled: true,
    tier: "SPECIALIST",
    geography: "AU",
    notes: "Australian arts and cultural-sector coverage.",
  },
  {
    slug: "gamesindustry",
    name: "GamesIndustry.biz",
    sector: "gaming",
    feedUrl: "https://www.gamesindustry.biz/feed",
    publisherDomain: "gamesindustry.biz",
    enabled: true,
    tier: "PRIMARY_TRADE",
    geography: "GB",
    notes: "Games business trade coverage.",
  },
  {
    slug: "game-developer",
    name: "Game Developer",
    sector: "gaming",
    feedUrl: "https://www.gamedeveloper.com/rss.xml",
    publisherDomain: "gamedeveloper.com",
    enabled: true,
    tier: "PRIMARY_TRADE",
    geography: "US",
    notes: "Game-development business and workforce news.",
  },
  {
    slug: "pc-gamer",
    name: "PC Gamer",
    sector: "gaming",
    feedUrl: "https://www.pcgamer.com/rss/",
    publisherDomain: "pcgamer.com",
    enabled: true,
    tier: "SPECIALIST",
    geography: null,
    notes: "PC gaming news.",
  },
  {
    slug: "polygon",
    name: "Polygon",
    sector: "gaming",
    feedUrl: "https://www.polygon.com/rss/index.xml",
    publisherDomain: "polygon.com",
    enabled: true,
    tier: "SPECIALIST",
    geography: "US",
    notes: "Gaming and entertainment coverage.",
  },
  {
    slug: "techcrunch-ai",
    name: "TechCrunch AI",
    sector: "ai-policy",
    feedUrl: "https://techcrunch.com/category/artificial-intelligence/feed/",
    publisherDomain: "techcrunch.com",
    enabled: true,
    tier: "MAJOR_GENERAL",
    geography: "US",
    notes: "AI product, policy, and business reporting.",
  },
  {
    slug: "ars-technology-lab",
    name: "Ars Technica Technology Lab",
    sector: "ai-policy",
    feedUrl: "https://feeds.arstechnica.com/arstechnica/technology-lab",
    publisherDomain: "arstechnica.com",
    enabled: true,
    tier: "SPECIALIST",
    geography: "US",
    notes: "Technology and AI reporting.",
  },
  {
    slug: "eff-updates",
    name: "Electronic Frontier Foundation",
    sector: "ai-policy",
    feedUrl: "https://www.eff.org/rss/updates.xml",
    publisherDomain: "eff.org",
    enabled: true,
    tier: "OFFICIAL",
    geography: "US",
    notes: "Digital rights and policy advocacy updates.",
  },
  {
    slug: "guardian-culture",
    name: "The Guardian Culture",
    sector: "industry-events",
    feedUrl: "https://www.theguardian.com/culture/rss",
    publisherDomain: "theguardian.com",
    enabled: true,
    tier: "MAJOR_GENERAL",
    geography: "GB",
    notes: "Cross-sector culture reporting.",
  },
] as const satisfies readonly RssFeedDefinition[];

export function enabledRssFeeds(): RssFeedDefinition[] {
  return RSS_FEEDS.filter((feed) => feed.enabled);
}
