import type { MediaSectorSlug } from "@/data-sources/news/media-types";

export type RssSourceTier =
  "PRIMARY_TRADE" | "MAJOR_GENERAL" | "SPECIALIST" | "OFFICIAL";

export const MEDIA_EVIDENCE_ROLES = [
  "PRIMARY_DOCUMENT",
  "JOURNALISTIC_REPORTING",
  "SPECIALIST_ANALYSIS",
] as const;

export type MediaEvidenceRole = (typeof MEDIA_EVIDENCE_ROLES)[number];

export const MEDIA_SOURCE_PERSPECTIVES = [
  "OFFICIAL",
  "JOURNALISTIC",
  "LEGAL",
  "POLICY",
  "RESEARCH",
  "ADVOCACY",
  "LABOUR",
  "INDUSTRY",
  "ANALYTICAL",
  "ACADEMIC",
  "TRANSLATION",
  "LICENSING",
] as const;

export type MediaSourcePerspective = (typeof MEDIA_SOURCE_PERSPECTIVES)[number];

export const MEDIA_SOURCE_SPECIALISMS = [
  "AI_POLICY",
  "COPYRIGHT",
  "CREATOR_RIGHTS",
  "COMPETITION",
  "CONSUMER_PROTECTION",
  "STANDARDS",
  "DIGITAL_MARKETS",
  "AI_LABOUR",
  "AI_INFRASTRUCTURE",
  "NATIONAL_SECURITY",
  "EXPORT_CONTROLS",
  "COURTS",
  "FRONTIER_AI",
  "COMPUTE",
  "SEMICONDUCTORS",
  "CHINA",
  "MARKET_POWER",
  "SURVEILLANCE",
  "INDUSTRIAL_POLICY",
  "AI_TRAINING",
  "FAIR_USE",
  "TEXT_DATA_MINING",
  "LICENSING",
  "AI_ADOPTION",
  "PRODUCTIVITY",
  "CAPABILITY_EVALUATION",
  "AUTOMATION",
  "WORKPLACE_POWER",
  "LAYOFFS",
  "MANAGEMENT",
  "CREATIVE_LABOUR",
  "CHINA_AI",
  "AI_GOVERNANCE",
  "TECHNICAL_STANDARDS",
  "AI_COMPANIES",
  "PUBLISHING_CONTRACTS",
  "SCHOLARLY_PUBLISHING",
  "OPEN_CONTENT",
  "TRAINING_DATA",
  "PROVENANCE",
  "CREATOR_CHOICE",
  "CULTURAL_HERITAGE",
] as const;

export type MediaSourceSpecialism = (typeof MEDIA_SOURCE_SPECIALISMS)[number];

export type RssSchedulingGroup =
  "CURATED_MEDIA" | "INSTITUTIONAL" | "SPECIALIST";

export type RssFeedDefinition = {
  slug: string;
  name: string;
  sector: MediaSectorSlug;
  feedUrl: string;
  publisherDomain: string;
  enabled: boolean;
  tier: RssSourceTier;
  geography: string | null;
  evidenceRole: MediaEvidenceRole;
  sourcePerspective: MediaSourcePerspective;
  sourcePerspectives?: readonly MediaSourcePerspective[];
  jurisdiction: string | null;
  sourceSpecialisms: readonly MediaSourceSpecialism[];
  schedulingGroup: RssSchedulingGroup;
  dataSourceSlug?: string;
  maxItemsPerRun?: number;
  maxItemsToParse?: number;
  maximumAgeHours?: number;
  translationStatus?: "TRANSLATED_OR_SUMMARISED";
  notes: string;
};

export const RSS_FEEDS = [
  {
    slug: "music-business-worldwide",
    name: "Music Business Worldwide",
    sector: "music",
    feedUrl: "https://www.musicbusinessworldwide.com/feed/",
    publisherDomain: "musicbusinessworldwide.com",
    enabled: true,
    tier: "PRIMARY_TRADE",
    geography: null,
    evidenceRole: "JOURNALISTIC_REPORTING",
    sourcePerspective: "INDUSTRY",
    jurisdiction: null,
    sourceSpecialisms: [],
    schedulingGroup: "CURATED_MEDIA",
    notes: "Music business trade coverage.",
  },
  {
    slug: "billboard",
    name: "Billboard",
    sector: "music",
    feedUrl: "https://www.billboard.com/feed/",
    publisherDomain: "billboard.com",
    enabled: true,
    tier: "PRIMARY_TRADE",
    geography: "US",
    evidenceRole: "JOURNALISTIC_REPORTING",
    sourcePerspective: "INDUSTRY",
    jurisdiction: "US",
    sourceSpecialisms: [],
    schedulingGroup: "CURATED_MEDIA",
    notes: "Music industry and chart news.",
  },
  {
    slug: "nme-music",
    name: "NME Music",
    sector: "music",
    feedUrl: "https://www.nme.com/news/music/feed",
    publisherDomain: "nme.com",
    enabled: true,
    tier: "SPECIALIST",
    geography: "GB",
    evidenceRole: "JOURNALISTIC_REPORTING",
    sourcePerspective: "JOURNALISTIC",
    jurisdiction: "GB",
    sourceSpecialisms: [],
    schedulingGroup: "CURATED_MEDIA",
    notes: "Music news feed.",
  },
  {
    slug: "pitchfork-news",
    name: "Pitchfork News",
    sector: "music",
    feedUrl: "https://pitchfork.com/feed/feed-news/rss",
    publisherDomain: "pitchfork.com",
    enabled: true,
    tier: "SPECIALIST",
    geography: "US",
    evidenceRole: "JOURNALISTIC_REPORTING",
    sourcePerspective: "JOURNALISTIC",
    jurisdiction: "US",
    sourceSpecialisms: [],
    schedulingGroup: "CURATED_MEDIA",
    notes: "Recorded and live music news.",
  },
  {
    slug: "variety-film",
    name: "Variety Film",
    sector: "film",
    feedUrl: "https://variety.com/v/film/feed/",
    publisherDomain: "variety.com",
    enabled: true,
    tier: "PRIMARY_TRADE",
    geography: "US",
    evidenceRole: "JOURNALISTIC_REPORTING",
    sourcePerspective: "INDUSTRY",
    jurisdiction: "US",
    sourceSpecialisms: [],
    schedulingGroup: "CURATED_MEDIA",
    notes: "Film trade reporting.",
  },
  {
    slug: "deadline-film",
    name: "Deadline Film",
    sector: "film",
    feedUrl: "https://deadline.com/v/film/feed/",
    publisherDomain: "deadline.com",
    enabled: true,
    tier: "PRIMARY_TRADE",
    geography: "US",
    evidenceRole: "JOURNALISTIC_REPORTING",
    sourcePerspective: "INDUSTRY",
    jurisdiction: "US",
    sourceSpecialisms: [],
    schedulingGroup: "CURATED_MEDIA",
    notes: "Film business and production news.",
  },
  {
    slug: "hollywood-reporter-movies",
    name: "The Hollywood Reporter Movies",
    sector: "film",
    feedUrl: "https://www.hollywoodreporter.com/c/movies/movie-news/feed/",
    publisherDomain: "hollywoodreporter.com",
    enabled: true,
    tier: "PRIMARY_TRADE",
    geography: "US",
    evidenceRole: "JOURNALISTIC_REPORTING",
    sourcePerspective: "INDUSTRY",
    jurisdiction: "US",
    sourceSpecialisms: [],
    schedulingGroup: "CURATED_MEDIA",
    notes: "Movie industry news.",
  },
  {
    slug: "indiewire-film",
    name: "IndieWire Film",
    sector: "film",
    feedUrl: "https://www.indiewire.com/c/film/news/feed/",
    publisherDomain: "indiewire.com",
    enabled: true,
    tier: "SPECIALIST",
    geography: "US",
    evidenceRole: "JOURNALISTIC_REPORTING",
    sourcePerspective: "JOURNALISTIC",
    jurisdiction: "US",
    sourceSpecialisms: [],
    schedulingGroup: "CURATED_MEDIA",
    notes: "Independent film and industry news.",
  },
  {
    slug: "playbill",
    name: "Playbill",
    sector: "theatre",
    feedUrl: "https://playbill.com/rss/news",
    publisherDomain: "playbill.com",
    enabled: true,
    tier: "SPECIALIST",
    geography: "US",
    evidenceRole: "JOURNALISTIC_REPORTING",
    sourcePerspective: "JOURNALISTIC",
    jurisdiction: "US",
    sourceSpecialisms: [],
    schedulingGroup: "CURATED_MEDIA",
    notes: "Theatre news.",
  },
  {
    slug: "broadwayworld",
    name: "BroadwayWorld",
    sector: "theatre",
    feedUrl: "https://www.broadwayworld.com/rss/newsroom.cfm",
    publisherDomain: "broadwayworld.com",
    enabled: false,
    tier: "SPECIALIST",
    geography: "US",
    evidenceRole: "JOURNALISTIC_REPORTING",
    sourcePerspective: "JOURNALISTIC",
    jurisdiction: "US",
    sourceSpecialisms: [],
    schedulingGroup: "CURATED_MEDIA",
    notes: "Disabled after live validation returned HTTP 403.",
  },
  {
    slug: "theatermania",
    name: "TheaterMania",
    sector: "theatre",
    feedUrl: "https://www.theatermania.com/feed/",
    publisherDomain: "theatermania.com",
    enabled: false,
    tier: "SPECIALIST",
    geography: "US",
    evidenceRole: "JOURNALISTIC_REPORTING",
    sourcePerspective: "JOURNALISTIC",
    jurisdiction: "US",
    sourceSpecialisms: [],
    schedulingGroup: "CURATED_MEDIA",
    notes: "Disabled after the endpoint returned no parseable feed items.",
  },
  {
    slug: "artshub-australia",
    name: "ArtsHub Australia",
    sector: "theatre",
    feedUrl: "https://www.artshub.com.au/feed/",
    publisherDomain: "artshub.com.au",
    enabled: true,
    tier: "SPECIALIST",
    geography: "AU",
    evidenceRole: "JOURNALISTIC_REPORTING",
    sourcePerspective: "JOURNALISTIC",
    jurisdiction: "AU",
    sourceSpecialisms: [],
    schedulingGroup: "CURATED_MEDIA",
    notes: "Australian arts and cultural-sector coverage.",
  },
  {
    slug: "gamesindustry",
    name: "GamesIndustry.biz",
    sector: "gaming",
    feedUrl: "https://www.gamesindustry.biz/feed",
    publisherDomain: "gamesindustry.biz",
    enabled: true,
    tier: "PRIMARY_TRADE",
    geography: "GB",
    evidenceRole: "JOURNALISTIC_REPORTING",
    sourcePerspective: "INDUSTRY",
    jurisdiction: "GB",
    sourceSpecialisms: [],
    schedulingGroup: "CURATED_MEDIA",
    notes: "Games business trade coverage.",
  },
  {
    slug: "game-developer",
    name: "Game Developer",
    sector: "gaming",
    feedUrl: "https://www.gamedeveloper.com/rss.xml",
    publisherDomain: "gamedeveloper.com",
    enabled: true,
    tier: "PRIMARY_TRADE",
    geography: "US",
    evidenceRole: "JOURNALISTIC_REPORTING",
    sourcePerspective: "INDUSTRY",
    jurisdiction: "US",
    sourceSpecialisms: [],
    schedulingGroup: "CURATED_MEDIA",
    notes: "Game-development business and workforce news.",
  },
  {
    slug: "pc-gamer",
    name: "PC Gamer",
    sector: "gaming",
    feedUrl: "https://www.pcgamer.com/rss/",
    publisherDomain: "pcgamer.com",
    enabled: true,
    tier: "SPECIALIST",
    geography: null,
    evidenceRole: "JOURNALISTIC_REPORTING",
    sourcePerspective: "JOURNALISTIC",
    jurisdiction: null,
    sourceSpecialisms: [],
    schedulingGroup: "CURATED_MEDIA",
    notes: "PC gaming news.",
  },
  {
    slug: "polygon",
    name: "Polygon",
    sector: "gaming",
    feedUrl: "https://www.polygon.com/rss/index.xml",
    publisherDomain: "polygon.com",
    enabled: true,
    tier: "SPECIALIST",
    geography: "US",
    evidenceRole: "JOURNALISTIC_REPORTING",
    sourcePerspective: "JOURNALISTIC",
    jurisdiction: "US",
    sourceSpecialisms: [],
    schedulingGroup: "CURATED_MEDIA",
    notes: "Gaming and entertainment coverage.",
  },
  {
    slug: "techcrunch-ai",
    name: "TechCrunch AI",
    sector: "ai-policy",
    feedUrl: "https://techcrunch.com/category/artificial-intelligence/feed/",
    publisherDomain: "techcrunch.com",
    enabled: true,
    tier: "MAJOR_GENERAL",
    geography: "US",
    evidenceRole: "JOURNALISTIC_REPORTING",
    sourcePerspective: "JOURNALISTIC",
    jurisdiction: "US",
    sourceSpecialisms: ["AI_POLICY", "DIGITAL_MARKETS"],
    schedulingGroup: "CURATED_MEDIA",
    notes: "AI product, policy, and business reporting.",
  },
  {
    slug: "ars-technology-lab",
    name: "Ars Technica Technology Lab",
    sector: "ai-policy",
    feedUrl: "https://feeds.arstechnica.com/arstechnica/technology-lab",
    publisherDomain: "arstechnica.com",
    enabled: true,
    tier: "SPECIALIST",
    geography: "US",
    evidenceRole: "JOURNALISTIC_REPORTING",
    sourcePerspective: "JOURNALISTIC",
    jurisdiction: "US",
    sourceSpecialisms: ["AI_POLICY", "DIGITAL_MARKETS"],
    schedulingGroup: "CURATED_MEDIA",
    notes: "Technology and AI reporting.",
  },
  {
    slug: "eff-updates",
    name: "Electronic Frontier Foundation",
    sector: "ai-policy",
    feedUrl: "https://www.eff.org/rss/updates.xml",
    publisherDomain: "eff.org",
    enabled: true,
    tier: "OFFICIAL",
    geography: "US",
    evidenceRole: "SPECIALIST_ANALYSIS",
    sourcePerspective: "ADVOCACY",
    jurisdiction: "US",
    sourceSpecialisms: ["AI_POLICY", "COPYRIGHT", "CREATOR_RIGHTS"],
    schedulingGroup: "CURATED_MEDIA",
    notes: "Digital rights and policy advocacy updates.",
  },
  {
    slug: "guardian-culture",
    name: "The Guardian Culture",
    sector: "industry-events",
    feedUrl: "https://www.theguardian.com/culture/rss",
    publisherDomain: "theguardian.com",
    enabled: true,
    tier: "MAJOR_GENERAL",
    geography: "GB",
    evidenceRole: "JOURNALISTIC_REPORTING",
    sourcePerspective: "JOURNALISTIC",
    jurisdiction: "GB",
    sourceSpecialisms: [],
    schedulingGroup: "CURATED_MEDIA",
    notes: "Cross-sector culture reporting.",
  },
  {
    slug: "copyright-newsnet",
    name: "U.S. Copyright Office NewsNet",
    sector: "ai-policy",
    feedUrl: "https://www.copyright.gov/rss/newsnet.xml",
    publisherDomain: "copyright.gov",
    enabled: true,
    tier: "OFFICIAL",
    geography: "US",
    evidenceRole: "PRIMARY_DOCUMENT",
    sourcePerspective: "OFFICIAL",
    jurisdiction: "US",
    sourceSpecialisms: ["AI_POLICY", "COPYRIGHT", "CREATOR_RIGHTS"],
    schedulingGroup: "INSTITUTIONAL",
    dataSourceSlug: "copyright-newsnet",
    notes: "Official Copyright Office NewsNet announcements.",
  },
  {
    slug: "cfpb-newsroom",
    name: "CFPB Newsroom",
    sector: "ai-policy",
    feedUrl: "https://www.consumerfinance.gov/about-us/newsroom/feed/",
    publisherDomain: "consumerfinance.gov",
    enabled: true,
    tier: "OFFICIAL",
    geography: "US",
    evidenceRole: "PRIMARY_DOCUMENT",
    sourcePerspective: "OFFICIAL",
    jurisdiction: "US",
    sourceSpecialisms: ["CONSUMER_PROTECTION", "DIGITAL_MARKETS"],
    schedulingGroup: "INSTITUTIONAL",
    dataSourceSlug: "cfpb-newsroom",
    notes: "Official Consumer Financial Protection Bureau newsroom releases.",
  },
  {
    slug: "ftc-competition",
    name: "FTC Competition Press Releases",
    sector: "ai-policy",
    feedUrl: "https://www.ftc.gov/feeds/press-release-competition.xml",
    publisherDomain: "ftc.gov",
    enabled: true,
    tier: "OFFICIAL",
    geography: "US",
    evidenceRole: "PRIMARY_DOCUMENT",
    sourcePerspective: "OFFICIAL",
    jurisdiction: "US",
    sourceSpecialisms: ["COMPETITION", "DIGITAL_MARKETS", "AI_POLICY"],
    schedulingGroup: "INSTITUTIONAL",
    dataSourceSlug: "ftc-competition",
    notes: "Official FTC competition press releases only.",
  },
  {
    slug: "ftc-consumer-protection",
    name: "FTC Consumer Protection Press Releases",
    sector: "ai-policy",
    feedUrl: "https://www.ftc.gov/feeds/press-release-consumer-protection.xml",
    publisherDomain: "ftc.gov",
    enabled: true,
    tier: "OFFICIAL",
    geography: "US",
    evidenceRole: "PRIMARY_DOCUMENT",
    sourcePerspective: "OFFICIAL",
    jurisdiction: "US",
    sourceSpecialisms: ["CONSUMER_PROTECTION", "DIGITAL_MARKETS", "AI_POLICY"],
    schedulingGroup: "INSTITUTIONAL",
    dataSourceSlug: "ftc-consumer-protection",
    notes: "Official FTC consumer-protection press releases only.",
  },
  {
    slug: "nist-information-technology",
    name: "NIST Information Technology",
    sector: "ai-policy",
    feedUrl:
      "https://www.nist.gov/news-events/information%20technology/rss.xml",
    publisherDomain: "nist.gov",
    enabled: true,
    tier: "OFFICIAL",
    geography: "US",
    evidenceRole: "PRIMARY_DOCUMENT",
    sourcePerspective: "OFFICIAL",
    jurisdiction: "US",
    sourceSpecialisms: ["AI_POLICY", "STANDARDS"],
    schedulingGroup: "INSTITUTIONAL",
    dataSourceSlug: "nist-information-technology",
    notes: "Official NIST information-technology news and publications.",
  },
  {
    slug: "uk-dsit",
    name: "UK Department for Science, Innovation and Technology",
    sector: "ai-policy",
    feedUrl:
      "https://www.gov.uk/government/organisations/department-for-science-innovation-and-technology.atom",
    publisherDomain: "gov.uk",
    enabled: true,
    tier: "OFFICIAL",
    geography: "GB",
    evidenceRole: "PRIMARY_DOCUMENT",
    sourcePerspective: "OFFICIAL",
    jurisdiction: "GB",
    sourceSpecialisms: ["AI_POLICY", "DIGITAL_MARKETS", "STANDARDS"],
    schedulingGroup: "INSTITUTIONAL",
    dataSourceSlug: "uk-dsit",
    notes: "Official GOV.UK DSIT publication feed.",
  },
  {
    slug: "uk-ipo",
    name: "UK Intellectual Property Office",
    sector: "ai-policy",
    feedUrl:
      "https://www.gov.uk/government/organisations/intellectual-property-office.atom",
    publisherDomain: "gov.uk",
    enabled: true,
    tier: "OFFICIAL",
    geography: "GB",
    evidenceRole: "PRIMARY_DOCUMENT",
    sourcePerspective: "OFFICIAL",
    jurisdiction: "GB",
    sourceSpecialisms: ["AI_POLICY", "COPYRIGHT", "CREATOR_RIGHTS"],
    schedulingGroup: "INSTITUTIONAL",
    dataSourceSlug: "uk-ipo",
    notes: "Official GOV.UK Intellectual Property Office publication feed.",
  },
  {
    slug: "uk-cma",
    name: "UK Competition and Markets Authority",
    sector: "ai-policy",
    feedUrl:
      "https://www.gov.uk/government/organisations/competition-and-markets-authority.atom",
    publisherDomain: "gov.uk",
    enabled: true,
    tier: "OFFICIAL",
    geography: "GB",
    evidenceRole: "PRIMARY_DOCUMENT",
    sourcePerspective: "OFFICIAL",
    jurisdiction: "GB",
    sourceSpecialisms: [
      "AI_POLICY",
      "COMPETITION",
      "CONSUMER_PROTECTION",
      "DIGITAL_MARKETS",
    ],
    schedulingGroup: "INSTITUTIONAL",
    dataSourceSlug: "uk-cma",
    notes: "Official GOV.UK CMA publication feed.",
  },
  {
    slug: "eu-dg-connect",
    name: "European Commission DG CONNECT",
    sector: "ai-policy",
    feedUrl:
      "https://ec.europa.eu/commission/presscorner/api/rss?language=en&pagesize=20&dept=CONNECT",
    publisherDomain: "ec.europa.eu",
    enabled: true,
    tier: "OFFICIAL",
    geography: "EU",
    evidenceRole: "PRIMARY_DOCUMENT",
    sourcePerspective: "OFFICIAL",
    jurisdiction: "EU",
    sourceSpecialisms: [
      "AI_POLICY",
      "COMPETITION",
      "DIGITAL_MARKETS",
      "STANDARDS",
    ],
    schedulingGroup: "INSTITUTIONAL",
    dataSourceSlug: "eu-dg-connect",
    notes: "Official European Commission DG CONNECT press-corner feed.",
  },
  {
    slug: "tech-policy-press",
    name: "Tech Policy Press",
    sector: "ai-policy",
    feedUrl: "https://www.techpolicy.press/rss/feed.xml",
    publisherDomain: "techpolicy.press",
    enabled: true,
    tier: "SPECIALIST",
    geography: null,
    evidenceRole: "SPECIALIST_ANALYSIS",
    sourcePerspective: "POLICY",
    sourcePerspectives: ["POLICY", "JOURNALISTIC"],
    jurisdiction: "GLOBAL",
    sourceSpecialisms: [
      "AI_POLICY",
      "DIGITAL_MARKETS",
      "AI_LABOUR",
      "COPYRIGHT",
      "COMPETITION",
      "AI_INFRASTRUCTURE",
    ],
    schedulingGroup: "SPECIALIST",
    dataSourceSlug: "tech-policy-press",
    maxItemsPerRun: 20,
    maxItemsToParse: 100,
    maximumAgeHours: 72,
    notes:
      "Specialist technology-policy analysis; the unusually large feed is capped to 20 items and 72 hours per run.",
  },
  {
    slug: "lawfare-cybersecurity-tech",
    name: "Lawfare — Cybersecurity & Tech",
    sector: "ai-policy",
    feedUrl: "https://www.lawfaremedia.org/feeds/cybersecurity-tech",
    publisherDomain: "lawfaremedia.org",
    enabled: true,
    tier: "SPECIALIST",
    geography: "US",
    evidenceRole: "SPECIALIST_ANALYSIS",
    sourcePerspective: "LEGAL",
    sourcePerspectives: ["LEGAL", "POLICY"],
    jurisdiction: "US / GLOBAL",
    sourceSpecialisms: [
      "AI_POLICY",
      "NATIONAL_SECURITY",
      "EXPORT_CONTROLS",
      "DIGITAL_MARKETS",
      "COURTS",
    ],
    schedulingGroup: "SPECIALIST",
    dataSourceSlug: "lawfare-cybersecurity-tech",
    maxItemsPerRun: 30,
    maximumAgeHours: 168,
    notes: "Legal and policy analysis from Lawfare's technology feed.",
  },
  {
    slug: "cset",
    name: "Center for Security and Emerging Technology",
    sector: "ai-policy",
    feedUrl: "https://cset.georgetown.edu/feed/",
    publisherDomain: "cset.georgetown.edu",
    enabled: true,
    tier: "SPECIALIST",
    geography: "US",
    evidenceRole: "SPECIALIST_ANALYSIS",
    sourcePerspective: "RESEARCH",
    sourcePerspectives: ["RESEARCH", "POLICY"],
    jurisdiction: "US / GLOBAL / CHINA",
    sourceSpecialisms: [
      "FRONTIER_AI",
      "COMPUTE",
      "SEMICONDUCTORS",
      "EXPORT_CONTROLS",
      "AI_LABOUR",
      "CHINA",
      "AI_POLICY",
    ],
    schedulingGroup: "SPECIALIST",
    dataSourceSlug: "cset",
    maxItemsPerRun: 30,
    maximumAgeHours: 168,
    notes:
      "CSET research and commentary remain specialist analysis because item-level primary-document detection is not reliably encoded in the feed.",
  },
  {
    slug: "ai-now-institute",
    name: "AI Now Institute",
    sector: "ai-policy",
    feedUrl: "https://ainowinstitute.org/feed/",
    publisherDomain: "ainowinstitute.org",
    enabled: true,
    tier: "SPECIALIST",
    geography: "US",
    evidenceRole: "SPECIALIST_ANALYSIS",
    sourcePerspective: "RESEARCH",
    sourcePerspectives: ["RESEARCH", "ADVOCACY"],
    jurisdiction: "US / GLOBAL",
    sourceSpecialisms: [
      "AI_LABOUR",
      "MARKET_POWER",
      "AI_INFRASTRUCTURE",
      "SURVEILLANCE",
      "INDUSTRIAL_POLICY",
      "AI_POLICY",
    ],
    schedulingGroup: "SPECIALIST",
    dataSourceSlug: "ai-now-institute",
    maxItemsPerRun: 30,
    maximumAgeHours: 168,
    notes: "Research and advocacy analysis with explicit viewpoint metadata.",
  },
  {
    slug: "kluwer-copyright-blog",
    name: "Kluwer Copyright Blog",
    sector: "ai-policy",
    feedUrl: "https://legalblogs.wolterskluwer.com/copyright-blog/rss.xml",
    publisherDomain: "legalblogs.wolterskluwer.com",
    enabled: true,
    tier: "SPECIALIST",
    geography: "EU",
    evidenceRole: "SPECIALIST_ANALYSIS",
    sourcePerspective: "LEGAL",
    sourcePerspectives: ["LEGAL", "ACADEMIC"],
    jurisdiction: "GLOBAL / EU",
    sourceSpecialisms: [
      "COPYRIGHT",
      "AI_TRAINING",
      "FAIR_USE",
      "TEXT_DATA_MINING",
      "LICENSING",
      "CREATOR_RIGHTS",
    ],
    schedulingGroup: "SPECIALIST",
    dataSourceSlug: "kluwer-copyright-blog",
    maxItemsPerRun: 30,
    maximumAgeHours: 168,
    notes: "Legal and academic copyright analysis; feed summaries only.",
  },
  {
    slug: "normal-technology",
    name: "AI as Normal Technology",
    sector: "ai-policy",
    feedUrl: "https://www.normaltech.ai/feed",
    publisherDomain: "normaltech.ai",
    enabled: true,
    tier: "SPECIALIST",
    geography: "US",
    evidenceRole: "SPECIALIST_ANALYSIS",
    sourcePerspective: "ACADEMIC",
    sourcePerspectives: ["ACADEMIC", "ANALYTICAL"],
    jurisdiction: "US / GLOBAL",
    sourceSpecialisms: [
      "AI_ADOPTION",
      "AI_LABOUR",
      "PRODUCTIVITY",
      "CAPABILITY_EVALUATION",
      "AI_POLICY",
    ],
    schedulingGroup: "SPECIALIST",
    dataSourceSlug: "normal-technology",
    maxItemsPerRun: 30,
    maximumAgeHours: 168,
    notes: "Academic analysis of AI adoption, capabilities, and labour claims.",
  },
  {
    slug: "blood-in-the-machine",
    name: "Blood in the Machine",
    sector: "ai-policy",
    feedUrl: "https://www.bloodinthemachine.com/feed",
    publisherDomain: "bloodinthemachine.com",
    enabled: true,
    tier: "SPECIALIST",
    geography: "US",
    evidenceRole: "SPECIALIST_ANALYSIS",
    sourcePerspective: "LABOUR",
    sourcePerspectives: ["LABOUR", "JOURNALISTIC"],
    jurisdiction: "US / GLOBAL",
    sourceSpecialisms: [
      "AI_LABOUR",
      "AUTOMATION",
      "WORKPLACE_POWER",
      "LAYOFFS",
      "MANAGEMENT",
      "CREATIVE_LABOUR",
    ],
    schedulingGroup: "SPECIALIST",
    dataSourceSlug: "blood-in-the-machine",
    maxItemsPerRun: 30,
    maximumAgeHours: 168,
    notes: "Labour-oriented specialist reporting and analysis.",
  },
  {
    slug: "chinai",
    name: "ChinAI",
    sector: "ai-policy",
    feedUrl: "https://chinai.substack.com/feed",
    publisherDomain: "chinai.substack.com",
    enabled: true,
    tier: "SPECIALIST",
    geography: null,
    evidenceRole: "SPECIALIST_ANALYSIS",
    sourcePerspective: "ANALYTICAL",
    sourcePerspectives: ["ANALYTICAL", "TRANSLATION"],
    jurisdiction: "CHINA",
    sourceSpecialisms: [
      "CHINA_AI",
      "INDUSTRIAL_POLICY",
      "AI_GOVERNANCE",
      "TECHNICAL_STANDARDS",
      "AI_COMPANIES",
    ],
    schedulingGroup: "SPECIALIST",
    dataSourceSlug: "chinai",
    maxItemsPerRun: 30,
    maximumAgeHours: 168,
    translationStatus: "TRANSLATED_OR_SUMMARISED",
    notes:
      "Translated or summarised Chinese AI analysis; not equivalent to direct ingestion of the original source.",
  },
  {
    slug: "authors-alliance",
    name: "Authors Alliance",
    sector: "ai-policy",
    feedUrl: "https://www.authorsalliance.org/feed/",
    publisherDomain: "authorsalliance.org",
    enabled: true,
    tier: "SPECIALIST",
    geography: "US",
    evidenceRole: "SPECIALIST_ANALYSIS",
    sourcePerspective: "ADVOCACY",
    sourcePerspectives: ["ADVOCACY", "LEGAL"],
    jurisdiction: "US",
    sourceSpecialisms: [
      "CREATOR_RIGHTS",
      "COPYRIGHT",
      "FAIR_USE",
      "AI_TRAINING",
      "PUBLISHING_CONTRACTS",
      "SCHOLARLY_PUBLISHING",
    ],
    schedulingGroup: "SPECIALIST",
    dataSourceSlug: "authors-alliance",
    maxItemsPerRun: 30,
    maximumAgeHours: 168,
    notes: "Creator-rights advocacy and legal analysis.",
  },
  {
    slug: "creative-commons",
    name: "Creative Commons",
    sector: "ai-policy",
    feedUrl: "https://creativecommons.org/feed/",
    publisherDomain: "creativecommons.org",
    enabled: true,
    tier: "SPECIALIST",
    geography: null,
    evidenceRole: "SPECIALIST_ANALYSIS",
    sourcePerspective: "ADVOCACY",
    sourcePerspectives: ["ADVOCACY", "LICENSING"],
    jurisdiction: "GLOBAL",
    sourceSpecialisms: [
      "LICENSING",
      "OPEN_CONTENT",
      "TRAINING_DATA",
      "PROVENANCE",
      "CREATOR_CHOICE",
      "CULTURAL_HERITAGE",
    ],
    schedulingGroup: "SPECIALIST",
    dataSourceSlug: "creative-commons",
    maxItemsPerRun: 30,
    maximumAgeHours: 168,
    notes:
      "Licensing advocacy and analysis; feed membership is not automatic AI relevance.",
  },
] as const satisfies readonly RssFeedDefinition[];

export function enabledRssFeeds(
  schedulingGroup: RssSchedulingGroup = "CURATED_MEDIA",
): RssFeedDefinition[] {
  return RSS_FEEDS.filter(
    (feed) => feed.enabled && feed.schedulingGroup === schedulingGroup,
  );
}

export function institutionalRssFeeds(): RssFeedDefinition[] {
  return enabledRssFeeds("INSTITUTIONAL");
}

export function specialistRssFeeds(): RssFeedDefinition[] {
  return enabledRssFeeds("SPECIALIST");
}

export function getRssFeed(slug: string): RssFeedDefinition | undefined {
  return RSS_FEEDS.find((feed) => feed.slug === slug);
}

export function isInstitutionalRssSource(slug: string): boolean {
  return getRssFeed(slug)?.schedulingGroup === "INSTITUTIONAL";
}
