import type { MediaSectorSlug } from "@/data-sources/news/media-types";

export type RssSourceTier =
  "PRIMARY_TRADE" | "MAJOR_GENERAL" | "SPECIALIST" | "OFFICIAL";

export const MEDIA_EVIDENCE_ROLES = [
  "PRIMARY_DOCUMENT",
  "JOURNALISTIC_REPORTING",
  "SPECIALIST_ANALYSIS",
] as const;

export type MediaEvidenceRole = (typeof MEDIA_EVIDENCE_ROLES)[number];

export const MEDIA_SOURCE_PERSPECTIVES = [
  "OFFICIAL",
  "JOURNALISTIC",
  "LEGAL",
  "POLICY",
  "RESEARCH",
  "ADVOCACY",
  "LABOUR",
  "INDUSTRY",
  "ANALYTICAL",
] as const;

export type MediaSourcePerspective = (typeof MEDIA_SOURCE_PERSPECTIVES)[number];

export const MEDIA_SOURCE_SPECIALISMS = [
  "AI_POLICY",
  "COPYRIGHT",
  "CREATOR_RIGHTS",
  "COMPETITION",
  "CONSUMER_PROTECTION",
  "STANDARDS",
  "DIGITAL_MARKETS",
] as const;

export type MediaSourceSpecialism = (typeof MEDIA_SOURCE_SPECIALISMS)[number];

export type RssSchedulingGroup = "CURATED_MEDIA" | "INSTITUTIONAL";

export type RssFeedDefinition = {
  slug: string;
  name: string;
  sector: MediaSectorSlug;
  feedUrl: string;
  publisherDomain: string;
  enabled: boolean;
  tier: RssSourceTier;
  geography: string | null;
  evidenceRole: MediaEvidenceRole;
  sourcePerspective: MediaSourcePerspective;
  jurisdiction: string | null;
  sourceSpecialisms: readonly MediaSourceSpecialism[];
  schedulingGroup: RssSchedulingGroup;
  dataSourceSlug?: string;
  notes: string;
};

export const RSS_FEEDS = [
  {
    slug: "music-business-worldwide",
    name: "Music Business Worldwide",
    sector: "music",
    feedUrl: "https://www.musicbusinessworldwide.com/feed/",
    publisherDomain: "musicbusinessworldwide.com",
    enabled: true,
    tier: "PRIMARY_TRADE",
    geography: null,
    evidenceRole: "JOURNALISTIC_REPORTING",
    sourcePerspective: "INDUSTRY",
    jurisdiction: null,
    sourceSpecialisms: [],
    schedulingGroup: "CURATED_MEDIA",
    notes: "Music business trade coverage.",
  },
  {
    slug: "billboard",
    name: "Billboard",
    sector: "music",
    feedUrl: "https://www.billboard.com/feed/",
    publisherDomain: "billboard.com",
    enabled: true,
    tier: "PRIMARY_TRADE",
    geography: "US",
    evidenceRole: "JOURNALISTIC_REPORTING",
    sourcePerspective: "INDUSTRY",
    jurisdiction: "US",
    sourceSpecialisms: [],
    schedulingGroup: "CURATED_MEDIA",
    notes: "Music industry and chart news.",
  },
  {
    slug: "nme-music",
    name: "NME Music",
    sector: "music",
    feedUrl: "https://www.nme.com/news/music/feed",
    publisherDomain: "nme.com",
    enabled: true,
    tier: "SPECIALIST",
    geography: "GB",
    evidenceRole: "JOURNALISTIC_REPORTING",
    sourcePerspective: "JOURNALISTIC",
    jurisdiction: "GB",
    sourceSpecialisms: [],
    schedulingGroup: "CURATED_MEDIA",
    notes: "Music news feed.",
  },
  {
    slug: "pitchfork-news",
    name: "Pitchfork News",
    sector: "music",
    feedUrl: "https://pitchfork.com/feed/feed-news/rss",
    publisherDomain: "pitchfork.com",
    enabled: true,
    tier: "SPECIALIST",
    geography: "US",
    evidenceRole: "JOURNALISTIC_REPORTING",
    sourcePerspective: "JOURNALISTIC",
    jurisdiction: "US",
    sourceSpecialisms: [],
    schedulingGroup: "CURATED_MEDIA",
    notes: "Recorded and live music news.",
  },
  {
    slug: "variety-film",
    name: "Variety Film",
    sector: "film",
    feedUrl: "https://variety.com/v/film/feed/",
    publisherDomain: "variety.com",
    enabled: true,
    tier: "PRIMARY_TRADE",
    geography: "US",
    evidenceRole: "JOURNALISTIC_REPORTING",
    sourcePerspective: "INDUSTRY",
    jurisdiction: "US",
    sourceSpecialisms: [],
    schedulingGroup: "CURATED_MEDIA",
    notes: "Film trade reporting.",
  },
  {
    slug: "deadline-film",
    name: "Deadline Film",
    sector: "film",
    feedUrl: "https://deadline.com/v/film/feed/",
    publisherDomain: "deadline.com",
    enabled: true,
    tier: "PRIMARY_TRADE",
    geography: "US",
    evidenceRole: "JOURNALISTIC_REPORTING",
    sourcePerspective: "INDUSTRY",
    jurisdiction: "US",
    sourceSpecialisms: [],
    schedulingGroup: "CURATED_MEDIA",
    notes: "Film business and production news.",
  },
  {
    slug: "hollywood-reporter-movies",
    name: "The Hollywood Reporter Movies",
    sector: "film",
    feedUrl: "https://www.hollywoodreporter.com/c/movies/movie-news/feed/",
    publisherDomain: "hollywoodreporter.com",
    enabled: true,
    tier: "PRIMARY_TRADE",
    geography: "US",
    evidenceRole: "JOURNALISTIC_REPORTING",
    sourcePerspective: "INDUSTRY",
    jurisdiction: "US",
    sourceSpecialisms: [],
    schedulingGroup: "CURATED_MEDIA",
    notes: "Movie industry news.",
  },
  {
    slug: "indiewire-film",
    name: "IndieWire Film",
    sector: "film",
    feedUrl: "https://www.indiewire.com/c/film/news/feed/",
    publisherDomain: "indiewire.com",
    enabled: true,
    tier: "SPECIALIST",
    geography: "US",
    evidenceRole: "JOURNALISTIC_REPORTING",
    sourcePerspective: "JOURNALISTIC",
    jurisdiction: "US",
    sourceSpecialisms: [],
    schedulingGroup: "CURATED_MEDIA",
    notes: "Independent film and industry news.",
  },
  {
    slug: "playbill",
    name: "Playbill",
    sector: "theatre",
    feedUrl: "https://playbill.com/rss/news",
    publisherDomain: "playbill.com",
    enabled: true,
    tier: "SPECIALIST",
    geography: "US",
    evidenceRole: "JOURNALISTIC_REPORTING",
    sourcePerspective: "JOURNALISTIC",
    jurisdiction: "US",
    sourceSpecialisms: [],
    schedulingGroup: "CURATED_MEDIA",
    notes: "Theatre news.",
  },
  {
    slug: "broadwayworld",
    name: "BroadwayWorld",
    sector: "theatre",
    feedUrl: "https://www.broadwayworld.com/rss/newsroom.cfm",
    publisherDomain: "broadwayworld.com",
    enabled: false,
    tier: "SPECIALIST",
    geography: "US",
    evidenceRole: "JOURNALISTIC_REPORTING",
    sourcePerspective: "JOURNALISTIC",
    jurisdiction: "US",
    sourceSpecialisms: [],
    schedulingGroup: "CURATED_MEDIA",
    notes: "Disabled after live validation returned HTTP 403.",
  },
  {
    slug: "theatermania",
    name: "TheaterMania",
    sector: "theatre",
    feedUrl: "https://www.theatermania.com/feed/",
    publisherDomain: "theatermania.com",
    enabled: false,
    tier: "SPECIALIST",
    geography: "US",
    evidenceRole: "JOURNALISTIC_REPORTING",
    sourcePerspective: "JOURNALISTIC",
    jurisdiction: "US",
    sourceSpecialisms: [],
    schedulingGroup: "CURATED_MEDIA",
    notes: "Disabled after the endpoint returned no parseable feed items.",
  },
  {
    slug: "artshub-australia",
    name: "ArtsHub Australia",
    sector: "theatre",
    feedUrl: "https://www.artshub.com.au/feed/",
    publisherDomain: "artshub.com.au",
    enabled: true,
    tier: "SPECIALIST",
    geography: "AU",
    evidenceRole: "JOURNALISTIC_REPORTING",
    sourcePerspective: "JOURNALISTIC",
    jurisdiction: "AU",
    sourceSpecialisms: [],
    schedulingGroup: "CURATED_MEDIA",
    notes: "Australian arts and cultural-sector coverage.",
  },
  {
    slug: "gamesindustry",
    name: "GamesIndustry.biz",
    sector: "gaming",
    feedUrl: "https://www.gamesindustry.biz/feed",
    publisherDomain: "gamesindustry.biz",
    enabled: true,
    tier: "PRIMARY_TRADE",
    geography: "GB",
    evidenceRole: "JOURNALISTIC_REPORTING",
    sourcePerspective: "INDUSTRY",
    jurisdiction: "GB",
    sourceSpecialisms: [],
    schedulingGroup: "CURATED_MEDIA",
    notes: "Games business trade coverage.",
  },
  {
    slug: "game-developer",
    name: "Game Developer",
    sector: "gaming",
    feedUrl: "https://www.gamedeveloper.com/rss.xml",
    publisherDomain: "gamedeveloper.com",
    enabled: true,
    tier: "PRIMARY_TRADE",
    geography: "US",
    evidenceRole: "JOURNALISTIC_REPORTING",
    sourcePerspective: "INDUSTRY",
    jurisdiction: "US",
    sourceSpecialisms: [],
    schedulingGroup: "CURATED_MEDIA",
    notes: "Game-development business and workforce news.",
  },
  {
    slug: "pc-gamer",
    name: "PC Gamer",
    sector: "gaming",
    feedUrl: "https://www.pcgamer.com/rss/",
    publisherDomain: "pcgamer.com",
    enabled: true,
    tier: "SPECIALIST",
    geography: null,
    evidenceRole: "JOURNALISTIC_REPORTING",
    sourcePerspective: "JOURNALISTIC",
    jurisdiction: null,
    sourceSpecialisms: [],
    schedulingGroup: "CURATED_MEDIA",
    notes: "PC gaming news.",
  },
  {
    slug: "polygon",
    name: "Polygon",
    sector: "gaming",
    feedUrl: "https://www.polygon.com/rss/index.xml",
    publisherDomain: "polygon.com",
    enabled: true,
    tier: "SPECIALIST",
    geography: "US",
    evidenceRole: "JOURNALISTIC_REPORTING",
    sourcePerspective: "JOURNALISTIC",
    jurisdiction: "US",
    sourceSpecialisms: [],
    schedulingGroup: "CURATED_MEDIA",
    notes: "Gaming and entertainment coverage.",
  },
  {
    slug: "techcrunch-ai",
    name: "TechCrunch AI",
    sector: "ai-policy",
    feedUrl: "https://techcrunch.com/category/artificial-intelligence/feed/",
    publisherDomain: "techcrunch.com",
    enabled: true,
    tier: "MAJOR_GENERAL",
    geography: "US",
    evidenceRole: "JOURNALISTIC_REPORTING",
    sourcePerspective: "JOURNALISTIC",
    jurisdiction: "US",
    sourceSpecialisms: ["AI_POLICY", "DIGITAL_MARKETS"],
    schedulingGroup: "CURATED_MEDIA",
    notes: "AI product, policy, and business reporting.",
  },
  {
    slug: "ars-technology-lab",
    name: "Ars Technica Technology Lab",
    sector: "ai-policy",
    feedUrl: "https://feeds.arstechnica.com/arstechnica/technology-lab",
    publisherDomain: "arstechnica.com",
    enabled: true,
    tier: "SPECIALIST",
    geography: "US",
    evidenceRole: "JOURNALISTIC_REPORTING",
    sourcePerspective: "JOURNALISTIC",
    jurisdiction: "US",
    sourceSpecialisms: ["AI_POLICY", "DIGITAL_MARKETS"],
    schedulingGroup: "CURATED_MEDIA",
    notes: "Technology and AI reporting.",
  },
  {
    slug: "eff-updates",
    name: "Electronic Frontier Foundation",
    sector: "ai-policy",
    feedUrl: "https://www.eff.org/rss/updates.xml",
    publisherDomain: "eff.org",
    enabled: true,
    tier: "OFFICIAL",
    geography: "US",
    evidenceRole: "SPECIALIST_ANALYSIS",
    sourcePerspective: "ADVOCACY",
    jurisdiction: "US",
    sourceSpecialisms: ["AI_POLICY", "COPYRIGHT", "CREATOR_RIGHTS"],
    schedulingGroup: "CURATED_MEDIA",
    notes: "Digital rights and policy advocacy updates.",
  },
  {
    slug: "guardian-culture",
    name: "The Guardian Culture",
    sector: "industry-events",
    feedUrl: "https://www.theguardian.com/culture/rss",
    publisherDomain: "theguardian.com",
    enabled: true,
    tier: "MAJOR_GENERAL",
    geography: "GB",
    evidenceRole: "JOURNALISTIC_REPORTING",
    sourcePerspective: "JOURNALISTIC",
    jurisdiction: "GB",
    sourceSpecialisms: [],
    schedulingGroup: "CURATED_MEDIA",
    notes: "Cross-sector culture reporting.",
  },
  {
    slug: "copyright-newsnet",
    name: "U.S. Copyright Office NewsNet",
    sector: "ai-policy",
    feedUrl: "https://www.copyright.gov/rss/newsnet.xml",
    publisherDomain: "copyright.gov",
    enabled: true,
    tier: "OFFICIAL",
    geography: "US",
    evidenceRole: "PRIMARY_DOCUMENT",
    sourcePerspective: "OFFICIAL",
    jurisdiction: "US",
    sourceSpecialisms: ["AI_POLICY", "COPYRIGHT", "CREATOR_RIGHTS"],
    schedulingGroup: "INSTITUTIONAL",
    dataSourceSlug: "copyright-newsnet",
    notes: "Official Copyright Office NewsNet announcements.",
  },
  {
    slug: "cfpb-newsroom",
    name: "CFPB Newsroom",
    sector: "ai-policy",
    feedUrl: "https://www.consumerfinance.gov/about-us/newsroom/feed/",
    publisherDomain: "consumerfinance.gov",
    enabled: true,
    tier: "OFFICIAL",
    geography: "US",
    evidenceRole: "PRIMARY_DOCUMENT",
    sourcePerspective: "OFFICIAL",
    jurisdiction: "US",
    sourceSpecialisms: ["CONSUMER_PROTECTION", "DIGITAL_MARKETS"],
    schedulingGroup: "INSTITUTIONAL",
    dataSourceSlug: "cfpb-newsroom",
    notes: "Official Consumer Financial Protection Bureau newsroom releases.",
  },
  {
    slug: "ftc-competition",
    name: "FTC Competition Press Releases",
    sector: "ai-policy",
    feedUrl: "https://www.ftc.gov/feeds/press-release-competition.xml",
    publisherDomain: "ftc.gov",
    enabled: true,
    tier: "OFFICIAL",
    geography: "US",
    evidenceRole: "PRIMARY_DOCUMENT",
    sourcePerspective: "OFFICIAL",
    jurisdiction: "US",
    sourceSpecialisms: ["COMPETITION", "DIGITAL_MARKETS", "AI_POLICY"],
    schedulingGroup: "INSTITUTIONAL",
    dataSourceSlug: "ftc-competition",
    notes: "Official FTC competition press releases only.",
  },
  {
    slug: "ftc-consumer-protection",
    name: "FTC Consumer Protection Press Releases",
    sector: "ai-policy",
    feedUrl: "https://www.ftc.gov/feeds/press-release-consumer-protection.xml",
    publisherDomain: "ftc.gov",
    enabled: true,
    tier: "OFFICIAL",
    geography: "US",
    evidenceRole: "PRIMARY_DOCUMENT",
    sourcePerspective: "OFFICIAL",
    jurisdiction: "US",
    sourceSpecialisms: ["CONSUMER_PROTECTION", "DIGITAL_MARKETS", "AI_POLICY"],
    schedulingGroup: "INSTITUTIONAL",
    dataSourceSlug: "ftc-consumer-protection",
    notes: "Official FTC consumer-protection press releases only.",
  },
  {
    slug: "nist-information-technology",
    name: "NIST Information Technology",
    sector: "ai-policy",
    feedUrl:
      "https://www.nist.gov/news-events/information%20technology/rss.xml",
    publisherDomain: "nist.gov",
    enabled: true,
    tier: "OFFICIAL",
    geography: "US",
    evidenceRole: "PRIMARY_DOCUMENT",
    sourcePerspective: "OFFICIAL",
    jurisdiction: "US",
    sourceSpecialisms: ["AI_POLICY", "STANDARDS"],
    schedulingGroup: "INSTITUTIONAL",
    dataSourceSlug: "nist-information-technology",
    notes: "Official NIST information-technology news and publications.",
  },
  {
    slug: "uk-dsit",
    name: "UK Department for Science, Innovation and Technology",
    sector: "ai-policy",
    feedUrl:
      "https://www.gov.uk/government/organisations/department-for-science-innovation-and-technology.atom",
    publisherDomain: "gov.uk",
    enabled: true,
    tier: "OFFICIAL",
    geography: "GB",
    evidenceRole: "PRIMARY_DOCUMENT",
    sourcePerspective: "OFFICIAL",
    jurisdiction: "GB",
    sourceSpecialisms: ["AI_POLICY", "DIGITAL_MARKETS", "STANDARDS"],
    schedulingGroup: "INSTITUTIONAL",
    dataSourceSlug: "uk-dsit",
    notes: "Official GOV.UK DSIT publication feed.",
  },
  {
    slug: "uk-ipo",
    name: "UK Intellectual Property Office",
    sector: "ai-policy",
    feedUrl:
      "https://www.gov.uk/government/organisations/intellectual-property-office.atom",
    publisherDomain: "gov.uk",
    enabled: true,
    tier: "OFFICIAL",
    geography: "GB",
    evidenceRole: "PRIMARY_DOCUMENT",
    sourcePerspective: "OFFICIAL",
    jurisdiction: "GB",
    sourceSpecialisms: ["AI_POLICY", "COPYRIGHT", "CREATOR_RIGHTS"],
    schedulingGroup: "INSTITUTIONAL",
    dataSourceSlug: "uk-ipo",
    notes: "Official GOV.UK Intellectual Property Office publication feed.",
  },
  {
    slug: "uk-cma",
    name: "UK Competition and Markets Authority",
    sector: "ai-policy",
    feedUrl:
      "https://www.gov.uk/government/organisations/competition-and-markets-authority.atom",
    publisherDomain: "gov.uk",
    enabled: true,
    tier: "OFFICIAL",
    geography: "GB",
    evidenceRole: "PRIMARY_DOCUMENT",
    sourcePerspective: "OFFICIAL",
    jurisdiction: "GB",
    sourceSpecialisms: [
      "AI_POLICY",
      "COMPETITION",
      "CONSUMER_PROTECTION",
      "DIGITAL_MARKETS",
    ],
    schedulingGroup: "INSTITUTIONAL",
    dataSourceSlug: "uk-cma",
    notes: "Official GOV.UK CMA publication feed.",
  },
  {
    slug: "eu-dg-connect",
    name: "European Commission DG CONNECT",
    sector: "ai-policy",
    feedUrl:
      "https://ec.europa.eu/commission/presscorner/api/rss?language=en&pagesize=20&dept=CONNECT",
    publisherDomain: "ec.europa.eu",
    enabled: true,
    tier: "OFFICIAL",
    geography: "EU",
    evidenceRole: "PRIMARY_DOCUMENT",
    sourcePerspective: "OFFICIAL",
    jurisdiction: "EU",
    sourceSpecialisms: [
      "AI_POLICY",
      "COMPETITION",
      "DIGITAL_MARKETS",
      "STANDARDS",
    ],
    schedulingGroup: "INSTITUTIONAL",
    dataSourceSlug: "eu-dg-connect",
    notes: "Official European Commission DG CONNECT press-corner feed.",
  },
] as const satisfies readonly RssFeedDefinition[];

export function enabledRssFeeds(
  schedulingGroup: RssSchedulingGroup = "CURATED_MEDIA",
): RssFeedDefinition[] {
  return RSS_FEEDS.filter(
    (feed) => feed.enabled && feed.schedulingGroup === schedulingGroup,
  );
}

export function institutionalRssFeeds(): RssFeedDefinition[] {
  return enabledRssFeeds("INSTITUTIONAL");
}

export function getRssFeed(slug: string): RssFeedDefinition | undefined {
  return RSS_FEEDS.find((feed) => feed.slug === slug);
}

export function isInstitutionalRssSource(slug: string): boolean {
  return getRssFeed(slug)?.schedulingGroup === "INSTITUTIONAL";
}
