import type { CountryCode, SectorSlug } from "@/lib/constants";
import type { ImplementationStatus } from "@/data-sources/status";
import type {
  BaseUrlEnvironmentKey,
  SecretEnvironmentKey,
} from "@/lib/env-schema";
import type {
  MediaEvidenceRole,
  MediaSourcePerspective,
  MediaSourceSpecialism,
} from "@/data-sources/news/rss-registry";

export type SourceDefinitionShape = {
  slug: string;
  name: string;
  provider: string;
  baseUrlEnvironmentKey: BaseUrlEnvironmentKey;
  requiredCredentialEnvironmentKeys: readonly SecretEnvironmentKey[];
  countries: readonly CountryCode[];
  sectors: readonly SectorSlug[];
  requiresAuthentication: boolean;
  implementationStatus: ImplementationStatus;
  sourceUrl?: string;
  evidenceRole?: MediaEvidenceRole;
  sourcePerspective?: MediaSourcePerspective;
  sourcePerspectives?: readonly MediaSourcePerspective[];
  jurisdiction?: string;
  sourceSpecialisms?: readonly MediaSourceSpecialism[];
};

const ALL_COUNTRIES = ["AU", "US", "GB", "CA", "NZ", "EU"] as const;
const ALL_SECTORS = [
  "consumer-spending",
  "music",
  "film",
  "theatre",
  "gaming",
  "ai-policy",
  "industry-events",
] as const;

export const SOURCE_DEFINITIONS = [
  {
    slug: "abs",
    name: "ABS",
    provider: "Australian Bureau of Statistics",
    baseUrlEnvironmentKey: "ABS_BASE_URL",
    requiredCredentialEnvironmentKeys: [],
    countries: ["AU"],
    sectors: ["consumer-spending"],
    requiresAuthentication: false,
    implementationStatus: "implemented",
  },
  {
    slug: "bea",
    name: "BEA",
    provider: "U.S. Bureau of Economic Analysis",
    baseUrlEnvironmentKey: "BEA_BASE_URL",
    requiredCredentialEnvironmentKeys: ["BEA_API_KEY"],
    countries: ["US"],
    sectors: ["consumer-spending", "music"],
    requiresAuthentication: true,
    implementationStatus: "implemented",
  },
  {
    slug: "fred",
    name: "FRED",
    provider: "Federal Reserve Bank of St. Louis",
    baseUrlEnvironmentKey: "FRED_BASE_URL",
    requiredCredentialEnvironmentKeys: ["FRED_API_KEY"],
    countries: ["US"],
    sectors: ["consumer-spending"],
    requiresAuthentication: true,
    implementationStatus: "implemented",
  },
  {
    slug: "ons",
    name: "ONS",
    provider: "Office for National Statistics",
    baseUrlEnvironmentKey: "ONS_BASE_URL",
    requiredCredentialEnvironmentKeys: [],
    countries: ["GB"],
    sectors: ["consumer-spending"],
    requiresAuthentication: false,
    implementationStatus: "implemented",
  },
  {
    slug: "eurostat",
    name: "EU Structural Benchmark",
    provider: "European Commission",
    baseUrlEnvironmentKey: "EUROSTAT_BASE_URL",
    requiredCredentialEnvironmentKeys: [],
    countries: ["EU"],
    sectors: ["consumer-spending"],
    requiresAuthentication: false,
    implementationStatus: "implemented",
  },
  {
    slug: "statcan",
    name: "Statistics Canada",
    provider: "Government of Canada",
    baseUrlEnvironmentKey: "STATCAN_BASE_URL",
    requiredCredentialEnvironmentKeys: [],
    countries: ["CA"],
    sectors: ["consumer-spending"],
    requiresAuthentication: false,
    implementationStatus: "implemented",
  },
  {
    slug: "stats-nz",
    name: "Stats NZ",
    provider: "Statistics New Zealand",
    baseUrlEnvironmentKey: "STATS_NZ_BASE_URL",
    requiredCredentialEnvironmentKeys: ["STATS_NZ_API_KEY"],
    countries: ["NZ"],
    sectors: ["consumer-spending"],
    requiresAuthentication: true,
    implementationStatus: "not-implemented",
  },
  {
    slug: "gdelt",
    name: "GDELT",
    provider: "GDELT Project",
    baseUrlEnvironmentKey: "GDELT_BASE_URL",
    requiredCredentialEnvironmentKeys: [],
    countries: ["AU", "US", "GB", "CA"],
    sectors: ["music", "film", "theatre", "gaming", "industry-events"],
    requiresAuthentication: false,
    implementationStatus: "implemented",
  },
  {
    slug: "ticketmaster",
    name: "Ticketmaster Discovery",
    provider: "Ticketmaster",
    baseUrlEnvironmentKey: "TICKETMASTER_BASE_URL",
    requiredCredentialEnvironmentKeys: ["TICKETMASTER_API_KEY"],
    countries: ["AU", "US", "GB", "CA"],
    sectors: ["music", "theatre", "film", "industry-events"],
    requiresAuthentication: true,
    implementationStatus: "implemented",
  },
  {
    slug: "eventbrite",
    name: "Eventbrite",
    provider: "Eventbrite",
    baseUrlEnvironmentKey: "EVENTBRITE_BASE_URL",
    requiredCredentialEnvironmentKeys: ["EVENTBRITE_PRIVATE_TOKEN"],
    countries: ALL_COUNTRIES,
    sectors: ["music", "theatre", "industry-events"],
    requiresAuthentication: true,
    implementationStatus: "not-implemented",
  },
  {
    slug: "steam",
    name: "Steam Web API",
    provider: "Valve",
    baseUrlEnvironmentKey: "STEAM_BASE_URL",
    requiredCredentialEnvironmentKeys: ["STEAM_WEB_API_KEY"],
    countries: ALL_COUNTRIES,
    sectors: ["gaming"],
    requiresAuthentication: true,
    implementationStatus: "implemented",
  },
  {
    slug: "igdb",
    name: "IGDB",
    provider: "Twitch",
    baseUrlEnvironmentKey: "IGDB_BASE_URL",
    requiredCredentialEnvironmentKeys: ["IGDB_CLIENT_ID", "IGDB_CLIENT_SECRET"],
    countries: ALL_COUNTRIES,
    sectors: ["gaming"],
    requiresAuthentication: true,
    implementationStatus: "implemented",
  },
  {
    slug: "thenewsapi",
    name: "TheNewsAPI",
    provider: "TheNewsAPI",
    baseUrlEnvironmentKey: "THENEWSAPI_BASE_URL",
    requiredCredentialEnvironmentKeys: ["THENEWSAPI_API_KEY"],
    countries: ALL_COUNTRIES,
    sectors: [
      "music",
      "film",
      "theatre",
      "gaming",
      "ai-policy",
      "industry-events",
    ],
    requiresAuthentication: true,
    implementationStatus: "implemented",
  },
  {
    slug: "rss",
    name: "Curated RSS Feeds",
    provider: "Publisher-exposed RSS and Atom feeds",
    baseUrlEnvironmentKey: "RSS_BASE_URL",
    requiredCredentialEnvironmentKeys: [],
    countries: ALL_COUNTRIES,
    sectors: [
      "music",
      "film",
      "theatre",
      "gaming",
      "ai-policy",
      "industry-events",
    ],
    requiresAuthentication: false,
    implementationStatus: "implemented",
  },
  {
    slug: "copyright-newsnet",
    name: "U.S. Copyright Office NewsNet",
    provider: "U.S. Copyright Office",
    baseUrlEnvironmentKey: "RSS_BASE_URL",
    requiredCredentialEnvironmentKeys: [],
    countries: ["US"],
    sectors: ["ai-policy"],
    requiresAuthentication: false,
    implementationStatus: "implemented",
    sourceUrl: "https://www.copyright.gov/rss/newsnet.xml",
    evidenceRole: "PRIMARY_DOCUMENT",
    sourcePerspective: "OFFICIAL",
    jurisdiction: "US",
    sourceSpecialisms: ["AI_POLICY", "COPYRIGHT", "CREATOR_RIGHTS"],
  },
  {
    slug: "cfpb-newsroom",
    name: "CFPB Newsroom",
    provider: "Consumer Financial Protection Bureau",
    baseUrlEnvironmentKey: "RSS_BASE_URL",
    requiredCredentialEnvironmentKeys: [],
    countries: ["US"],
    sectors: ["ai-policy"],
    requiresAuthentication: false,
    implementationStatus: "implemented",
    sourceUrl: "https://www.consumerfinance.gov/about-us/newsroom/feed/",
    evidenceRole: "PRIMARY_DOCUMENT",
    sourcePerspective: "OFFICIAL",
    jurisdiction: "US",
    sourceSpecialisms: ["CONSUMER_PROTECTION", "DIGITAL_MARKETS"],
  },
  {
    slug: "ftc-competition",
    name: "FTC Competition Press Releases",
    provider: "Federal Trade Commission",
    baseUrlEnvironmentKey: "RSS_BASE_URL",
    requiredCredentialEnvironmentKeys: [],
    countries: ["US"],
    sectors: ["ai-policy"],
    requiresAuthentication: false,
    implementationStatus: "implemented",
    sourceUrl: "https://www.ftc.gov/feeds/press-release-competition.xml",
    evidenceRole: "PRIMARY_DOCUMENT",
    sourcePerspective: "OFFICIAL",
    jurisdiction: "US",
    sourceSpecialisms: ["COMPETITION", "DIGITAL_MARKETS", "AI_POLICY"],
  },
  {
    slug: "ftc-consumer-protection",
    name: "FTC Consumer Protection Press Releases",
    provider: "Federal Trade Commission",
    baseUrlEnvironmentKey: "RSS_BASE_URL",
    requiredCredentialEnvironmentKeys: [],
    countries: ["US"],
    sectors: ["ai-policy"],
    requiresAuthentication: false,
    implementationStatus: "implemented",
    sourceUrl:
      "https://www.ftc.gov/feeds/press-release-consumer-protection.xml",
    evidenceRole: "PRIMARY_DOCUMENT",
    sourcePerspective: "OFFICIAL",
    jurisdiction: "US",
    sourceSpecialisms: ["CONSUMER_PROTECTION", "DIGITAL_MARKETS", "AI_POLICY"],
  },
  {
    slug: "nist-information-technology",
    name: "NIST Information Technology",
    provider: "National Institute of Standards and Technology",
    baseUrlEnvironmentKey: "RSS_BASE_URL",
    requiredCredentialEnvironmentKeys: [],
    countries: ["US"],
    sectors: ["ai-policy"],
    requiresAuthentication: false,
    implementationStatus: "implemented",
    sourceUrl:
      "https://www.nist.gov/news-events/information%20technology/rss.xml",
    evidenceRole: "PRIMARY_DOCUMENT",
    sourcePerspective: "OFFICIAL",
    jurisdiction: "US",
    sourceSpecialisms: ["AI_POLICY", "STANDARDS"],
  },
  {
    slug: "uk-dsit",
    name: "UK Department for Science, Innovation and Technology",
    provider: "UK Government",
    baseUrlEnvironmentKey: "RSS_BASE_URL",
    requiredCredentialEnvironmentKeys: [],
    countries: ["GB"],
    sectors: ["ai-policy"],
    requiresAuthentication: false,
    implementationStatus: "implemented",
    sourceUrl:
      "https://www.gov.uk/government/organisations/department-for-science-innovation-and-technology.atom",
    evidenceRole: "PRIMARY_DOCUMENT",
    sourcePerspective: "OFFICIAL",
    jurisdiction: "GB",
    sourceSpecialisms: ["AI_POLICY", "DIGITAL_MARKETS", "STANDARDS"],
  },
  {
    slug: "uk-ipo",
    name: "UK Intellectual Property Office",
    provider: "UK Government",
    baseUrlEnvironmentKey: "RSS_BASE_URL",
    requiredCredentialEnvironmentKeys: [],
    countries: ["GB"],
    sectors: ["ai-policy"],
    requiresAuthentication: false,
    implementationStatus: "implemented",
    sourceUrl:
      "https://www.gov.uk/government/organisations/intellectual-property-office.atom",
    evidenceRole: "PRIMARY_DOCUMENT",
    sourcePerspective: "OFFICIAL",
    jurisdiction: "GB",
    sourceSpecialisms: ["AI_POLICY", "COPYRIGHT", "CREATOR_RIGHTS"],
  },
  {
    slug: "uk-cma",
    name: "UK Competition and Markets Authority",
    provider: "UK Government",
    baseUrlEnvironmentKey: "RSS_BASE_URL",
    requiredCredentialEnvironmentKeys: [],
    countries: ["GB"],
    sectors: ["ai-policy"],
    requiresAuthentication: false,
    implementationStatus: "implemented",
    sourceUrl:
      "https://www.gov.uk/government/organisations/competition-and-markets-authority.atom",
    evidenceRole: "PRIMARY_DOCUMENT",
    sourcePerspective: "OFFICIAL",
    jurisdiction: "GB",
    sourceSpecialisms: [
      "AI_POLICY",
      "COMPETITION",
      "CONSUMER_PROTECTION",
      "DIGITAL_MARKETS",
    ],
  },
  {
    slug: "eu-dg-connect",
    name: "European Commission DG CONNECT",
    provider: "European Commission",
    baseUrlEnvironmentKey: "RSS_BASE_URL",
    requiredCredentialEnvironmentKeys: [],
    countries: ["EU"],
    sectors: ["ai-policy"],
    requiresAuthentication: false,
    implementationStatus: "implemented",
    sourceUrl:
      "https://ec.europa.eu/commission/presscorner/api/rss?language=en&pagesize=20&dept=CONNECT",
    evidenceRole: "PRIMARY_DOCUMENT",
    sourcePerspective: "OFFICIAL",
    jurisdiction: "EU",
    sourceSpecialisms: [
      "AI_POLICY",
      "COMPETITION",
      "DIGITAL_MARKETS",
      "STANDARDS",
    ],
  },
  {
    slug: "tech-policy-press",
    name: "Tech Policy Press",
    provider: "Tech Policy Press",
    baseUrlEnvironmentKey: "RSS_BASE_URL",
    requiredCredentialEnvironmentKeys: [],
    countries: ALL_COUNTRIES,
    sectors: ["ai-policy"],
    requiresAuthentication: false,
    implementationStatus: "implemented",
    sourceUrl: "https://www.techpolicy.press/rss/feed.xml",
    evidenceRole: "SPECIALIST_ANALYSIS",
    sourcePerspective: "POLICY",
    sourcePerspectives: ["POLICY", "JOURNALISTIC"],
    jurisdiction: "GLOBAL",
    sourceSpecialisms: [
      "AI_POLICY",
      "DIGITAL_MARKETS",
      "AI_LABOUR",
      "COPYRIGHT",
      "COMPETITION",
      "AI_INFRASTRUCTURE",
    ],
  },
  {
    slug: "lawfare-cybersecurity-tech",
    name: "Lawfare — Cybersecurity & Tech",
    provider: "Lawfare",
    baseUrlEnvironmentKey: "RSS_BASE_URL",
    requiredCredentialEnvironmentKeys: [],
    countries: ["US"],
    sectors: ["ai-policy"],
    requiresAuthentication: false,
    implementationStatus: "implemented",
    sourceUrl: "https://www.lawfaremedia.org/feeds/cybersecurity-tech",
    evidenceRole: "SPECIALIST_ANALYSIS",
    sourcePerspective: "LEGAL",
    sourcePerspectives: ["LEGAL", "POLICY"],
    jurisdiction: "US / GLOBAL",
    sourceSpecialisms: [
      "AI_POLICY",
      "NATIONAL_SECURITY",
      "EXPORT_CONTROLS",
      "DIGITAL_MARKETS",
      "COURTS",
    ],
  },
  {
    slug: "cset",
    name: "Center for Security and Emerging Technology",
    provider: "Georgetown University CSET",
    baseUrlEnvironmentKey: "RSS_BASE_URL",
    requiredCredentialEnvironmentKeys: [],
    countries: ["US"],
    sectors: ["ai-policy"],
    requiresAuthentication: false,
    implementationStatus: "implemented",
    sourceUrl: "https://cset.georgetown.edu/feed/",
    evidenceRole: "SPECIALIST_ANALYSIS",
    sourcePerspective: "RESEARCH",
    sourcePerspectives: ["RESEARCH", "POLICY"],
    jurisdiction: "US / GLOBAL / CHINA",
    sourceSpecialisms: [
      "FRONTIER_AI",
      "COMPUTE",
      "SEMICONDUCTORS",
      "EXPORT_CONTROLS",
      "AI_LABOUR",
      "CHINA",
      "AI_POLICY",
    ],
  },
  {
    slug: "ai-now-institute",
    name: "AI Now Institute",
    provider: "AI Now Institute",
    baseUrlEnvironmentKey: "RSS_BASE_URL",
    requiredCredentialEnvironmentKeys: [],
    countries: ["US"],
    sectors: ["ai-policy"],
    requiresAuthentication: false,
    implementationStatus: "implemented",
    sourceUrl: "https://ainowinstitute.org/feed/",
    evidenceRole: "SPECIALIST_ANALYSIS",
    sourcePerspective: "RESEARCH",
    sourcePerspectives: ["RESEARCH", "ADVOCACY"],
    jurisdiction: "US / GLOBAL",
    sourceSpecialisms: [
      "AI_LABOUR",
      "MARKET_POWER",
      "AI_INFRASTRUCTURE",
      "SURVEILLANCE",
      "INDUSTRIAL_POLICY",
      "AI_POLICY",
    ],
  },
  {
    slug: "kluwer-copyright-blog",
    name: "Kluwer Copyright Blog",
    provider: "Wolters Kluwer",
    baseUrlEnvironmentKey: "RSS_BASE_URL",
    requiredCredentialEnvironmentKeys: [],
    countries: ALL_COUNTRIES,
    sectors: ["ai-policy"],
    requiresAuthentication: false,
    implementationStatus: "implemented",
    sourceUrl: "https://legalblogs.wolterskluwer.com/copyright-blog/rss.xml",
    evidenceRole: "SPECIALIST_ANALYSIS",
    sourcePerspective: "LEGAL",
    sourcePerspectives: ["LEGAL", "ACADEMIC"],
    jurisdiction: "GLOBAL / EU",
    sourceSpecialisms: [
      "COPYRIGHT",
      "AI_TRAINING",
      "FAIR_USE",
      "TEXT_DATA_MINING",
      "LICENSING",
      "CREATOR_RIGHTS",
    ],
  },
  {
    slug: "normal-technology",
    name: "AI as Normal Technology",
    provider: "AI as Normal Technology",
    baseUrlEnvironmentKey: "RSS_BASE_URL",
    requiredCredentialEnvironmentKeys: [],
    countries: ["US"],
    sectors: ["ai-policy"],
    requiresAuthentication: false,
    implementationStatus: "implemented",
    sourceUrl: "https://www.normaltech.ai/feed",
    evidenceRole: "SPECIALIST_ANALYSIS",
    sourcePerspective: "ACADEMIC",
    sourcePerspectives: ["ACADEMIC", "ANALYTICAL"],
    jurisdiction: "US / GLOBAL",
    sourceSpecialisms: [
      "AI_ADOPTION",
      "AI_LABOUR",
      "PRODUCTIVITY",
      "CAPABILITY_EVALUATION",
      "AI_POLICY",
    ],
  },
  {
    slug: "blood-in-the-machine",
    name: "Blood in the Machine",
    provider: "Blood in the Machine",
    baseUrlEnvironmentKey: "RSS_BASE_URL",
    requiredCredentialEnvironmentKeys: [],
    countries: ["US"],
    sectors: ["ai-policy"],
    requiresAuthentication: false,
    implementationStatus: "implemented",
    sourceUrl: "https://www.bloodinthemachine.com/feed",
    evidenceRole: "SPECIALIST_ANALYSIS",
    sourcePerspective: "LABOUR",
    sourcePerspectives: ["LABOUR", "JOURNALISTIC"],
    jurisdiction: "US / GLOBAL",
    sourceSpecialisms: [
      "AI_LABOUR",
      "AUTOMATION",
      "WORKPLACE_POWER",
      "LAYOFFS",
      "MANAGEMENT",
      "CREATIVE_LABOUR",
    ],
  },
  {
    slug: "chinai",
    name: "ChinAI",
    provider: "ChinAI",
    baseUrlEnvironmentKey: "RSS_BASE_URL",
    requiredCredentialEnvironmentKeys: [],
    countries: ALL_COUNTRIES,
    sectors: ["ai-policy"],
    requiresAuthentication: false,
    implementationStatus: "implemented",
    sourceUrl: "https://chinai.substack.com/feed",
    evidenceRole: "SPECIALIST_ANALYSIS",
    sourcePerspective: "ANALYTICAL",
    sourcePerspectives: ["ANALYTICAL", "TRANSLATION"],
    jurisdiction: "CHINA",
    sourceSpecialisms: [
      "CHINA_AI",
      "INDUSTRIAL_POLICY",
      "AI_GOVERNANCE",
      "TECHNICAL_STANDARDS",
      "AI_COMPANIES",
    ],
  },
  {
    slug: "authors-alliance",
    name: "Authors Alliance",
    provider: "Authors Alliance",
    baseUrlEnvironmentKey: "RSS_BASE_URL",
    requiredCredentialEnvironmentKeys: [],
    countries: ["US"],
    sectors: ["ai-policy"],
    requiresAuthentication: false,
    implementationStatus: "implemented",
    sourceUrl: "https://www.authorsalliance.org/feed/",
    evidenceRole: "SPECIALIST_ANALYSIS",
    sourcePerspective: "ADVOCACY",
    sourcePerspectives: ["ADVOCACY", "LEGAL"],
    jurisdiction: "US",
    sourceSpecialisms: [
      "CREATOR_RIGHTS",
      "COPYRIGHT",
      "FAIR_USE",
      "AI_TRAINING",
      "PUBLISHING_CONTRACTS",
      "SCHOLARLY_PUBLISHING",
    ],
  },
  {
    slug: "creative-commons",
    name: "Creative Commons",
    provider: "Creative Commons",
    baseUrlEnvironmentKey: "RSS_BASE_URL",
    requiredCredentialEnvironmentKeys: [],
    countries: ALL_COUNTRIES,
    sectors: ["ai-policy"],
    requiresAuthentication: false,
    implementationStatus: "implemented",
    sourceUrl: "https://creativecommons.org/feed/",
    evidenceRole: "SPECIALIST_ANALYSIS",
    sourcePerspective: "ADVOCACY",
    sourcePerspectives: ["ADVOCACY", "LICENSING"],
    jurisdiction: "GLOBAL",
    sourceSpecialisms: [
      "LICENSING",
      "OPEN_CONTENT",
      "TRAINING_DATA",
      "PROVENANCE",
      "CREATOR_CHOICE",
      "CULTURAL_HERITAGE",
    ],
  },
  {
    slug: "mediastack",
    name: "Mediastack",
    provider: "APILayer",
    baseUrlEnvironmentKey: "MEDIASTACK_BASE_URL",
    requiredCredentialEnvironmentKeys: ["MEDIASTACK_API_KEY"],
    countries: ALL_COUNTRIES,
    sectors: ALL_SECTORS,
    requiresAuthentication: true,
    implementationStatus: "not-implemented",
  },
  {
    slug: "us-box-office",
    name: "US Box Office — Provisional",
    provider: "Kaggle community dataset",
    baseUrlEnvironmentKey: "US_BOX_OFFICE_BASE_URL",
    requiredCredentialEnvironmentKeys: [],
    countries: ["US"],
    sectors: ["film"],
    requiresAuthentication: false,
    implementationStatus: "implemented",
  },
  {
    slug: "broadway-business",
    name: "Broadway Business",
    provider: "Broadway Business",
    baseUrlEnvironmentKey: "BROADWAY_BUSINESS_BASE_URL",
    requiredCredentialEnvironmentKeys: [],
    countries: ["US"],
    sectors: ["theatre"],
    requiresAuthentication: false,
    implementationStatus: "implemented",
  },
  {
    slug: "bfi",
    name: "British Film Institute",
    provider: "British Film Institute",
    baseUrlEnvironmentKey: "BFI_BASE_URL",
    requiredCredentialEnvironmentKeys: [],
    countries: ["GB"],
    sectors: ["film"],
    requiresAuthentication: false,
    implementationStatus: "implemented",
  },
  {
    slug: "screen-australia",
    name: "Screen Australia Box Office",
    provider: "Screen Australia",
    baseUrlEnvironmentKey: "SCREEN_AUSTRALIA_BASE_URL",
    requiredCredentialEnvironmentKeys: [],
    countries: ["AU"],
    sectors: ["film"],
    requiresAuthentication: false,
    implementationStatus: "implemented",
  },
  {
    slug: "mvt",
    name: "Music Venue Trust",
    provider: "Music Venue Trust",
    baseUrlEnvironmentKey: "MVT_BASE_URL",
    requiredCredentialEnvironmentKeys: [],
    countries: ["GB"],
    sectors: ["music"],
    requiresAuthentication: false,
    implementationStatus: "implemented",
  },
  {
    slug: "census",
    name: "US Census Bureau",
    provider: "U.S. Census Bureau",
    baseUrlEnvironmentKey: "CENSUS_BASE_URL",
    requiredCredentialEnvironmentKeys: [],
    countries: ["US"],
    sectors: ["music"],
    requiresAuthentication: false,
    implementationStatus: "implemented",
  },
  {
    slug: "lpa",
    name: "Live Performance Australia",
    provider: "Live Performance Australia",
    baseUrlEnvironmentKey: "LPA_BASE_URL",
    requiredCredentialEnvironmentKeys: [],
    countries: ["AU"],
    sectors: ["theatre"],
    requiresAuthentication: false,
    implementationStatus: "implemented",
  },
  {
    slug: "luna-story-synthesis",
    name: "Luna Intelligence Synthesis",
    provider: "OpenAI",
    baseUrlEnvironmentKey: "OPENAI_BASE_URL",
    requiredCredentialEnvironmentKeys: ["OPENAI_API_KEY"],
    countries: ALL_COUNTRIES,
    sectors: ALL_SECTORS,
    requiresAuthentication: true,
    implementationStatus: "implemented",
    sourceUrl: "https://api.openai.com/v1/responses",
  },
] as const satisfies readonly SourceDefinitionShape[];

export type SourceDefinition = (typeof SOURCE_DEFINITIONS)[number] &
  SourceDefinitionShape;
export type SourceSlug = SourceDefinition["slug"];

export function getSourceDefinition(slug: SourceSlug): SourceDefinition {
  const source = SOURCE_DEFINITIONS.find(
    (definition) => definition.slug === slug,
  );

  if (!source) {
    throw new Error(`Unknown data source: ${slug}`);
  }

  return source;
}
